# Serenity Configuration
serenity.project.name=Moodle Test Automation Framework
serenity.take.screenshots=FOR_EACH_ACTION
webdriver.driver=chrome
headless.mode=false

# Feature directory path
serenity.requirements.dir=src/test/resources/features